##
## EPITECH PROJECT, 2025
## R-Type
## File description:
## epitech-mirroring.yml
##

name: Mirror Epitech Project

env:
  MIRROR_URL: git@github.com:EpitechPGE3-2025/G-CPP-500-MLH-5-1-rtype-1

on:
  push:
    branches:
      - main

jobs:
  push_to_mirror:
    name: Push to Mirror
    runs-on: ubuntu-latest
    if: github.repository != 'EpitechPGE3-2025/G-CPP-500-MLH-5-1-rtype-1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
